---
kind: pipeline
type: docker
name: default-build

steps:
  - name: check
    image: publicawesome/networks-check
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
  - name: collect
    image: publicawesome/stargaze:beta
    commands:
      - sh ./ci/check-gentx.sh
  - name: runner
    image: publicawesome/stargaze:beta
    detach: true
    commands:
      - apk add jq
      - sh ./run.sh
  - name: check_runner
    image: alpine:3
    commands:
      - apk add curl
      - apk add jq
      - sh ./check-running-node.sh

trigger:
  event:
    - pull_request

---
kind: signature
hmac: fe8e42c605a43d4d1706e8e6aca9f00802f08fad17d7091b416ff74bdecfbb35

...
