---
kind: pipeline
type: docker
name: default-build

steps:
  - name: check
    image: publicawesome/networks-check
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
  - name: collect
    image: publicawesome/stargaze:beta
    commands:
      - sh ./ci/check-gentx.sh
  - name: runner
    image: publicawesome/stargaze:beta
    detach: true
    commands:
      - apk add jq
      - sh ./ci/run.sh
  - name: check_runner
    image: alpine:3
    commands:
      - apk add curl
      - apk add jq
      - sh ./ci/check-running-node.sh
  - name: failure
    image: publicawesome/networks-check
    settings:
      failure: true
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    when:
      status: [failure]
trigger:
  event:
    - pull_request

---
kind: pipeline
type: docker
name: full_test

steps:
  - name: bootstrap
    pull: always
    image: publicawesome/stargaze:beta
    commands:
      - apk add tar jq
      - sh ./ci/bootstrap-full-test.sh
  - name: node0
    pull: always
    image: publicawesome/stargaze:beta
    commands:
      - starsd start --home $PWD/tmp/ci-testnet/node0/starsd 
trigger:
  branch:
    - feature/full-test
  event:
    - pull_request
    - push
---
kind: signature
hmac: e8947e6b657acf51292542e3fc1c05be4b176c14ea4cfea7d142ad45f2179d29

...
