---
kind: pipeline
type: docker
name: default-build

steps:
  - name: check
    image: publicawesome/networks-check
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
  - name: collect
    image: publicawesome/stargaze:beta
    commands:
      - sh ./ci/check-gentx.sh
  - name: runner
    image: publicawesome/stargaze:beta
    detach: true
    commands:
      - apk add jq
      - sh ./ci/run.sh
  - name: check_runner
    image: alpine:3
    commands:
      - apk add curl
      - apk add jq
      - sh ./ci/check-running-node.sh
  - name: failure
    image: publicawesome/networks-check
    settings:
      failure: true
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    when:
      status: [failure]
trigger:
  event:
    - pull_request

---
kind: pipeline
type: docker
name: full_test

steps:
  - name: bootstrap
    pull: always
    image: publicawesome/stargaze:beta
    commands:
      - apk add tar jq
      - sh ./ci/bootstrap-full-test.sh
  - name: node0
    detach: true
    image: publicawesome/stargaze:beta
    commands:
      - starsd start --home $PWD/tmp/ci-testnet/node0/starsd
  - name: node1
    detach: true
    image: publicawesome/stargaze:beta
    commands:
      - starsd start --home $PWD/tmp/ci-testnet/node1/starsd
  - name: node2
    detach: true
    image: publicawesome/stargaze:beta
    commands:
      - starsd start --home $PWD/tmp/ci-testnet/node2/starsd 
  - name: node3
    detach: true
    image: publicawesome/stargaze:beta
    commands:
      - starsd start --home $PWD/tmp/ci-testnet/node3/starsd
  - name: readiness
    image: publicawesome/stargaze-readiness-checker:latest
    settings:
      timeout: 900
      blocks: 101
      chain_list:
        - http://node0:26657
        - http://node1:26657
        - http://node2:26657
        - http://node3:26657
trigger:
  branch:
    - main
  event:
    - pull_request
    - push
---
kind: signature
hmac: 1098bf1eca8133cca3d258e1813959b1d0c17bd1712816d3d2d86ce34aed2582

...
