---
kind: pipeline
type: docker
name: default-build

steps:
  - name: check
    image: publicawesome/networks-check
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
  - name: collect
    image: publicawesome/stargaze:beta
    commands:
      - sh ./ci/check-gentx.sh
  - name: runner
    image: publicawesome/stargaze:beta
    detach: true
    commands:
      - apk add jq
      - sh ./ci/run.sh
  - name: check_runner
    image: alpine:3
    commands:
      - apk add curl
      - apk add jq
      - sh ./ci/check-running-node.sh
  - name: failure
    image: publicawesome/networks-check
    settings:
      failure: true
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    when:
      status: [failure]
trigger:
  event:
    - pull_request

---
kind: pipeline
type: docker
name: full test

steps:
  - name: bootstrap
    image: publicawesome/stargaze:beta
    commands:
      - apk add tar
      - sh ./ci/bootstrap-full-test.sh
trigger:
  branch:
    - feature/full-test
  event:
    - pull_request
    - push
---
kind: signature
hmac: fee9a0619a0a3938ce648de45e67648aa336d02226c78bcc52693087a7d1fddf

...
