---
kind: pipeline
type: docker
name: default-build

steps:
  - name: check
    image: publicawesome/networks-check
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
  - name: collect
    image: publicawesome/stargaze:beta
    commands:
      - sh ./ci/check-gentx.sh
  - name: stargaze
    image: publicawesome/stargaze:beta
    detach: true
    commands:
      - apk add jq
      - sh ./ci/run.sh
  - name: readiness
    image: publicawesome/stargaze-readiness-checker:latest
    settings:
      check_file: check-gen-tx
      timeout: 300
      blocks: 50
      chain_list:
        - http://stargaze:26657
trigger:
  event:
    - pull_request

---
kind: signature
hmac: 9afd811fda772678db07df5e3dabcf9d250255d6ab9cae5d3609c6331315664d

...
